name: analysis
description: A set of utility classes to make common use cases of using the Dart analyzer.
version: 0.0.1-alpha.3+hotfix
homepage: https://github.com/matanlurey/analysis
author: Matan Lurey <matanl@google.com>
dependencies:
  analyzer: ">=0.25.0+1 <0.26.0"
dev_dependencies:
  test: any
