name: analysis
description: A set of utility classes to make common use cases of using the Dart analyzer.
version: 0.0.1-alpha.6
homepage: https://github.com/matanlurey/analysis
author: Matan Lurey <matanl@google.com>
dependencies:
  analyzer: any
  quiver: any
dev_dependencies:
  test: any
